"""Relationship Validation Engine -- 3-way interaction validation.

For every triple generated by the broad hierarchical screen
(stage2_relval_triple_screen.py): tests genuine 3-way structure via the
lower-order (main effects + all pairwise effects) vs. full (adds a genuine
3-way binned term) grouped-CV comparison (triple_cv, extending v3_common's
fit_threeway/predict_threeway machinery, reused unmodified, with MAE
added), with a permutation-based empirical p-value (pooled null from
B_PERM target shuffles across the SAME candidate pool) and Benjamini-
Hochberg FDR as the primary acceptance gate, on top of grouped-fold
stability.
"""
from __future__ import annotations

import json
import time

import numpy as np
import pandas as pd

from src.explain.stage2_relval_common import (
    CACHE_DIR, R, RANDOM_STATE, benjamini_hochberg, empirical_pvalue, group_block_shuffle, load_locked_split,
    triple_cv,
)
from src.explain.stage2_v3_common import fit_threeway

B_PERM = 10
ALPHA_FDR = 0.05
MIN_FOLD_FRACTION_STRONG = 1.0    # was: absolute count 5 (dormant bug -- see audit; fraction is correct for candidates with <5 valid folds)
MIN_FOLD_FRACTION_MODERATE = 0.8  # was: absolute count 4


def main():
    split = load_locked_split()
    ds = split.ds
    y_train_arr = split.y_train.to_numpy()

    cand = pd.read_csv(f"{R}/stage2_runB_relationship_validation_triple_screen.csv")
    triples = list(zip(cand["parameter_A"], cand["parameter_B"], cand["parameter_C"]))
    channels_lookup = dict(zip(zip(cand["parameter_A"], cand["parameter_B"], cand["parameter_C"]), cand["generation_channels"]))
    print(f"3-way validation: {len(triples)} generated candidate triples")

    x_cache = {}
    def get_x(f):
        if f not in x_cache:
            x_cache[f] = split.X_train[ds.name_map[f]].to_numpy(dtype=np.float64)
        return x_cache[f]

    print("Real-target pass...")
    t0 = time.time()
    real_rows = []
    real_stat = {}
    for k, (a, b, c) in enumerate(triples):
        if a not in ds.name_map or b not in ds.name_map or c not in ds.name_map:
            continue
        xa, xb, xc = get_x(a), get_x(b), get_x(c)
        cv = triple_cv(xa, xb, xc, y_train_arr, split.folds, n_bins=2)
        if cv is None:
            continue
        full_fit = fit_threeway(xa, xb, xc, y_train_arr, n_bins=2)
        fg = full_fit["full_grid"]
        best = np.unravel_index(np.argmax(fg), fg.shape)
        worst = np.unravel_index(np.argmin(fg), fg.shape)
        bin_lab = lambda i: "high" if i == 1 else "low"
        real_rows.append({
            "parameter_A": a, "parameter_B": b, "parameter_C": c,
            "generation_channels": channels_lookup.get((a, b, c), ""),
            "lower_order_cv_rmse": round(cv["lower_cv_rmse"], 4), "full_cv_rmse": round(cv["full_cv_rmse"], 4),
            "delta_rmse": round(cv["delta_rmse"], 4),
            "lower_order_cv_mae": round(cv["lower_cv_mae"], 4), "full_cv_mae": round(cv["full_cv_mae"], 4),
            "delta_mae": round(cv["delta_mae"], 4),
            "lower_order_cv_r2": round(cv["lower_cv_r2"], 4), "full_cv_r2": round(cv["full_cv_r2"], 4),
            "delta_r2": round(cv["delta_r2"], 6),
            "folds_improved": f"{cv['folds_improved']}/{cv['n_folds']}",
            "high_yield_joint_condition": f"{a}={bin_lab(best[0])}, {b}={bin_lab(best[1])}, {c}={bin_lab(best[2])}",
            "low_yield_joint_condition": f"{a}={bin_lab(worst[0])}, {b}={bin_lab(worst[1])}, {c}={bin_lab(worst[2])}",
        })
        real_stat[(a, b, c)] = cv["delta_r2"]
        if (k + 1) % 2000 == 0:
            print(f"  {k+1}/{len(triples)} ({time.time()-t0:.0f}s elapsed)", flush=True)
    print(f"Real-target pass done in {time.time()-t0:.1f}s ({len(real_rows)} triples with valid CV)")

    print(f"\nRunning {B_PERM} shuffled-target permutations on the SAME {len(triples)}-triple pool...")
    null_pool = []
    t0 = time.time()
    groups_train = split.groups_train.to_numpy()
    for perm_i in range(B_PERM):
        rng = np.random.RandomState(RANDOM_STATE + 3000 + perm_i)
        y_shuf = group_block_shuffle(y_train_arr, groups_train, rng)
        for a, b, c in triples:
            if a not in ds.name_map or b not in ds.name_map or c not in ds.name_map:
                continue
            cv = triple_cv(get_x(a), get_x(b), get_x(c), y_shuf, split.folds, n_bins=2)
            if cv is not None:
                null_pool.append(cv["delta_r2"])
        print(f"  permutation {perm_i+1}/{B_PERM} done ({time.time()-t0:.0f}s elapsed, pool size={len(null_pool)})", flush=True)
    null_pool = np.array(null_pool)
    print(f"Permutation pass done in {time.time()-t0:.1f}s -- pooled null size={len(null_pool)}")
    effect_size_95th = float(np.percentile(null_pool, 95))
    print(f"Empirical null 95th percentile of delta_r2: {effect_size_95th:.6f}")

    df = pd.DataFrame(real_rows)
    pvals = np.array([empirical_pvalue(real_stat[(r["parameter_A"], r["parameter_B"], r["parameter_C"])], null_pool)
                       for _, r in df.iterrows()])
    qvals, accept = benjamini_hochberg(pvals, alpha=ALPHA_FDR)
    df["empirical_p_value"] = np.round(pvals, 6)
    df["bh_adjusted_q_value"] = np.round(qvals, 6)
    df["survives_fdr"] = accept

    def label_row(r):
        fi, fn = (int(x) for x in r["folds_improved"].split("/"))
        meaningful = r["delta_r2"] > effect_size_95th
        if not r["survives_fdr"]:
            return "INCONCLUSIVE", "fails FDR"
        if fn > 0 and (fi / fn) >= MIN_FOLD_FRACTION_STRONG and meaningful:
            return "STRONG", f"{fi}/{fn} folds improved, effect exceeds null 95th pctile, survives FDR"
        if fn > 0 and (fi / fn) >= MIN_FOLD_FRACTION_MODERATE and meaningful:
            return "MODERATE", f"{fi}/{fn} folds improved, effect exceeds null 95th pctile, survives FDR"
        if fi >= 2 or meaningful:
            return "WEAK", f"{fi}/{fn} folds improved, marginal effect"
        return "INCONCLUSIVE", "insufficient fold consistency or effect size"

    labels_reasons = df.apply(label_row, axis=1)
    df["confidence"] = [x[0] for x in labels_reasons]
    df["reason"] = [x[1] for x in labels_reasons]

    order = {"STRONG": 0, "MODERATE": 1, "WEAK": 2, "INCONCLUSIVE": 3}
    df = df.sort_values(["confidence", "delta_r2"], key=lambda s: s.map(order) if s.name == "confidence" else s,
                         ascending=[True, False])
    out_path = f"{R}/stage2_runB_relationship_validation_3way.csv"
    df.to_csv(out_path, index=False)
    print(f"\nSaved {out_path} ({len(df)} validated triples)")
    print(df["confidence"].value_counts().to_string())
    print(f"Hypotheses tested: {len(df)} | Survive FDR: {int(df['survives_fdr'].sum())}")

    with open(f"{CACHE_DIR}/triple_null_summary.json", "w") as f:
        json.dump({
            "family": "3way", "n_hypotheses": int(len(df)), "b_perm": B_PERM,
            "null_pool_size": int(len(null_pool)),
            "null_delta_r2_mean": float(np.mean(null_pool)), "null_delta_r2_95th_pctile": effect_size_95th,
            "null_delta_r2_99th_pctile": float(np.percentile(null_pool, 99)),
            "real_strong_count": int((df["confidence"] == "STRONG").sum()),
            "real_moderate_count": int((df["confidence"] == "MODERATE").sum()),
            "real_survives_fdr_count": int(df["survives_fdr"].sum()),
        }, f, indent=2)
    np.save(f"{CACHE_DIR}/triple_null_pool.npy", null_pool)

    print("\nTop 10 STRONG by delta_r2:")
    print(df[df["confidence"] == "STRONG"].head(10)[
        ["parameter_A", "parameter_B", "parameter_C", "delta_r2", "folds_improved", "bh_adjusted_q_value"]
    ].to_string(index=False))


if __name__ == "__main__":
    main()
